version: "3"

services:
  app:
    # Use the current directory to find out how to build the container (using the Dockerfile in this directory)
    build:
      context: .

    # Port mapping outside to inside the container
    ports:
      - "8000:8000"

    # Same for the volumes
    volumes:
      - ./app:/app

    # Run the Django server on this machine (container), port 8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    