version: "3"

services:
  app:
    # Use the current directory to find out how to build the container (using the Dockerfile in this directory)
    build:
      context: .

    # Port mapping outside to inside the container
    ports:
      - "8000:8000"

    # Same for the volumes
    volumes:
      - ./app:/app

    # Run the Django server on this machine (container), port 8000
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    # ENV variables for the app
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    
    # Make sure db is started first
    depends_on:
      - db

  db:
    # The image to start with
    image: postgres:10-alpine

    ports:
      - "5432:5432"

    # Variables expected by the Postgres docker image
    # In a true environment, you would expect Travis or Jenkins to set this variable during build
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

    